#!/usr/bin/env bash
# Redirection

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

new="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "s/server_name _\;/$new/" /etc/nginx/sites-available/default
sudo service nginx restart
