#!/usr/bin/env bash
# ha proxy cf

front="frontend init\n\tbind *:80\n\tdefault_backend back_init\n"
back="backend back_init\n\tbalance roundrobin\n\tserver 414211-web-01 3.90.70.250:80\n\tserver 414211-web-02 52.87.230.58:80"

echo -e "$front" >> /etc/haproxy/haproxy.cfg
echo -e "$back" >> /etc/haproxy/haproxy.cfg
