#!/usr/bin/env bash
# ha proxy cf

sudo apt -y install haproxy

front="frontend init\n\tbind *:80\n\tdefault_backend back_init\n"
back="backend back_init\n\tbalance roundrobin\n\tserver web-01 3.90.70.250:80\n\tserver web-02 52.87.230.58:80"

sudo echo -e "$front" >> /etc/haproxy/haproxy.cfg
sudo echo -e "$back" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
