#!/usr/bin/env bash
#debugging
sudo apt update
sudo apt-get -y install nginx
new="server {\n\tlisten *:80 default_server;}"
sudo sed -i "s/server {/$new/" /etc/nginx/sites-available/default
sudo service nginx restart
