#!/usr/bin/env bash
#ps with more infos
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --sort=-pid --forest
#ps aux --sort=-%cpu | awk '{printf "%s %s %s %s %s %s %s %s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $11}'
