#!/usr/bin/env bash
#signal
pkill "bash"
#pid=$(ps -eo pid,command)

#pid=$(echo "$pid" |grep "bash" | grep "./4-to_infinity_and_beyond" | cut -d ' ' -f2)
#if [ -n "$pid" ]
#then
#	pkill -2 -P $pid
#	echo "send"
#fi
