#!/usr/bin/env bash
#printing 'Best school' ten times using while loop
((i = 1))
while ((i <= 10))
do
	echo "Best School"
	if [[ $i == 9 ]]
        then
                echo "Hi"
        fi
	((i += 1))
done
